"""oportunidad seguimiento

Revision ID: 13aef446d2f6
Revises: 3568317481a7
Create Date: 2026-07-13 09:28:05.384169

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '13aef446d2f6'
down_revision: str | None = '3568317481a7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oportunidades', sa.Column('asunto', sa.String(length=255), nullable=True))
    op.add_column('oportunidades', sa.Column('valor_estimado', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('oportunidades', sa.Column('fecha_pedido_cliente', sa.Date(), nullable=True))
    op.add_column('oportunidades', sa.Column('fecha_enviado_compras', sa.Date(), nullable=True))
    op.add_column('oportunidades', sa.Column('fecha_enviado_cliente', sa.Date(), nullable=True))
    op.add_column('oportunidades', sa.Column('fecha_limite', sa.Date(), nullable=True))
    op.add_column('oportunidades', sa.Column('comentarios', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oportunidades', 'comentarios')
    op.drop_column('oportunidades', 'fecha_limite')
    op.drop_column('oportunidades', 'fecha_enviado_cliente')
    op.drop_column('oportunidades', 'fecha_enviado_compras')
    op.drop_column('oportunidades', 'fecha_pedido_cliente')
    op.drop_column('oportunidades', 'valor_estimado')
    op.drop_column('oportunidades', 'asunto')
    # ### end Alembic commands ###
