"""gmail per usuario

Revision ID: 1cbb4c1bd861
Revises: 8df3a2cafacc
Create Date: 2026-06-30 15:14:23.503089

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cbb4c1bd861'
down_revision: str | None = '8df3a2cafacc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('gmail_refresh_token', sa.Text(), nullable=True))
    op.add_column('usuarios', sa.Column('gmail_conectado_en', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'gmail_conectado_en')
    op.drop_column('usuarios', 'gmail_refresh_token')
    # ### end Alembic commands ###
