"""init schema

Revision ID: 234f51c692a1
Revises: 
Create Date: 2026-06-22 08:36:12.265838

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '234f51c692a1'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracion',
    sa.Column('clave', sa.String(length=120), nullable=False),
    sa.Column('valor', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('clave')
    )
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=80), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('unidad', sa.String(length=40), nullable=True),
    sa.Column('precio_base', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('categoria', sa.String(length=120), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('ultima_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productos_categoria'), 'productos', ['categoria'], unique=False)
    op.create_index(op.f('ix_productos_codigo'), 'productos', ['codigo'], unique=True)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('vendedor', 'admin', 'compras', name='rol_usuario'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razon_social', sa.String(length=255), nullable=False),
    sa.Column('cuit', sa.String(length=20), nullable=True),
    sa.Column('vendedor_asignado_id', sa.Integer(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vendedor_asignado_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_cuit'), 'clientes', ['cuit'], unique=False)
    op.create_index(op.f('ix_clientes_razon_social'), 'clientes', ['razon_social'], unique=False)
    op.create_table('notificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('leida', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contactos_cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('cargo', sa.String(length=120), nullable=True),
    sa.Column('rol_compra', sa.Enum('decisor', 'tecnico', 'compras', 'logistica', 'otro', name='rol_compra'), nullable=False),
    sa.Column('es_principal', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contactos_cliente_email'), 'contactos_cliente', ['email'], unique=False)
    op.create_table('dominios_cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('dominio', sa.String(length=255), nullable=False),
    sa.Column('es_principal_dominio', sa.Boolean(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dominios_cliente_dominio'), 'dominios_cliente', ['dominio'], unique=False)
    op.create_table('oportunidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('contacto_cliente_id', sa.Integer(), nullable=True),
    sa.Column('vendedor_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('nueva', 'requiere_aclaracion', 'en_compras', 'presupuestada', 'ganada', 'cargada_en_gbp', 'facturada', 'perdida', name='estado_oportunidad'), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_ultimo_movimiento', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fuente', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['contacto_cliente_id'], ['contactos_cliente.id'], ),
    sa.ForeignKeyConstraint(['vendedor_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oportunidades_estado'), 'oportunidades', ['estado'], unique=False)
    op.create_table('mails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gmail_thread_id', sa.String(length=255), nullable=True),
    sa.Column('gmail_message_id', sa.String(length=255), nullable=True),
    sa.Column('oportunidad_id', sa.Integer(), nullable=True),
    sa.Column('direccion', sa.Enum('entrante', 'saliente', name='direccion_mail'), nullable=False),
    sa.Column('de', sa.String(length=320), nullable=True),
    sa.Column('para', sa.String(length=500), nullable=True),
    sa.Column('asunto', sa.String(length=500), nullable=True),
    sa.Column('cuerpo', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=True),
    sa.Column('adjuntos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('datos_extraidos_ia', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['oportunidad_id'], ['oportunidades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mails_gmail_message_id'), 'mails', ['gmail_message_id'], unique=True)
    op.create_index(op.f('ix_mails_gmail_thread_id'), 'mails', ['gmail_thread_id'], unique=False)
    op.create_table('presupuestos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oportunidad_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('monto_total', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('condicion_pago', sa.String(length=40), nullable=True),
    sa.Column('plazo_entrega', sa.String(length=120), nullable=True),
    sa.Column('validez', sa.String(length=120), nullable=True),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('qr_url', sa.String(length=500), nullable=True),
    sa.Column('fecha_envio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_respuesta_cliente', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estado', sa.Enum('borrador', 'enviado', 'aceptado', 'rechazado', 'negociando', name='estado_presupuesto'), nullable=False),
    sa.Column('id_gbp_pedido', sa.String(length=80), nullable=True),
    sa.Column('id_gbp_factura', sa.String(length=80), nullable=True),
    sa.Column('fecha_validez', sa.Date(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['oportunidad_id'], ['oportunidades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_presupuestos_codigo'), 'presupuestos', ['codigo'], unique=True)
    op.create_index(op.f('ix_presupuestos_estado'), 'presupuestos', ['estado'], unique=False)
    op.create_index(op.f('ix_presupuestos_id_gbp_factura'), 'presupuestos', ['id_gbp_factura'], unique=False)
    op.create_index(op.f('ix_presupuestos_id_gbp_pedido'), 'presupuestos', ['id_gbp_pedido'], unique=False)
    op.create_table('recordatorios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('oportunidad_id', sa.Integer(), nullable=True),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('fecha_recordatorio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completado', sa.Boolean(), nullable=False),
    sa.Column('tipo', sa.Enum('manual', 'automatico_estado', 'automatico_inactividad', name='tipo_recordatorio'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['oportunidad_id'], ['oportunidades.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recordatorios_fecha_recordatorio'), 'recordatorios', ['fecha_recordatorio'], unique=False)
    op.create_table('solicitudes_compras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oportunidad_id', sa.Integer(), nullable=False),
    sa.Column('solicitante_id', sa.Integer(), nullable=False),
    sa.Column('requerimiento', sa.Text(), nullable=False),
    sa.Column('archivos_adjuntos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('condicion_pago', sa.Enum('dias_15', 'dias_30', 'dias_45', 'dias_60', 'dias_120', 'transferencia', name='condicion_pago'), nullable=True),
    sa.Column('importe_aproximado', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('fecha_limite', sa.Date(), nullable=True),
    sa.Column('presupuesto_gbp_referencia', sa.String(length=80), nullable=True),
    sa.Column('ccs_extra', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('fecha_envio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_respuesta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gmail_thread_id', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.Enum('enviada', 'respondida', 'cerrada', name='estado_solicitud'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['oportunidad_id'], ['oportunidades.id'], ),
    sa.ForeignKeyConstraint(['solicitante_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solicitudes_compras_gmail_thread_id'), 'solicitudes_compras', ['gmail_thread_id'], unique=False)
    op.create_table('adjuntos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mail_id', sa.Integer(), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('path_storage', sa.String(length=500), nullable=True),
    sa.Column('descripcion_ia', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mail_id'], ['mails.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('presupuesto_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('presupuesto_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('descuento_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('sku', sa.String(length=120), nullable=True),
    sa.Column('fabricante', sa.String(length=120), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['presupuesto_id'], ['presupuestos.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('respuestas_compras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitud_compras_id', sa.Integer(), nullable=False),
    sa.Column('fecha_recepcion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('contenido_raw', sa.Text(), nullable=True),
    sa.Column('datos_parseados_ia', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notas_compras', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['solicitud_compras_id'], ['solicitudes_compras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('respuestas_compras')
    op.drop_table('presupuesto_items')
    op.drop_table('adjuntos')
    op.drop_index(op.f('ix_solicitudes_compras_gmail_thread_id'), table_name='solicitudes_compras')
    op.drop_table('solicitudes_compras')
    op.drop_index(op.f('ix_recordatorios_fecha_recordatorio'), table_name='recordatorios')
    op.drop_table('recordatorios')
    op.drop_index(op.f('ix_presupuestos_id_gbp_pedido'), table_name='presupuestos')
    op.drop_index(op.f('ix_presupuestos_id_gbp_factura'), table_name='presupuestos')
    op.drop_index(op.f('ix_presupuestos_estado'), table_name='presupuestos')
    op.drop_index(op.f('ix_presupuestos_codigo'), table_name='presupuestos')
    op.drop_table('presupuestos')
    op.drop_index(op.f('ix_mails_gmail_thread_id'), table_name='mails')
    op.drop_index(op.f('ix_mails_gmail_message_id'), table_name='mails')
    op.drop_table('mails')
    op.drop_index(op.f('ix_oportunidades_estado'), table_name='oportunidades')
    op.drop_table('oportunidades')
    op.drop_index(op.f('ix_dominios_cliente_dominio'), table_name='dominios_cliente')
    op.drop_table('dominios_cliente')
    op.drop_index(op.f('ix_contactos_cliente_email'), table_name='contactos_cliente')
    op.drop_table('contactos_cliente')
    op.drop_table('notificaciones')
    op.drop_index(op.f('ix_clientes_razon_social'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_cuit'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_productos_codigo'), table_name='productos')
    op.drop_index(op.f('ix_productos_categoria'), table_name='productos')
    op.drop_table('productos')
    op.drop_table('configuracion')
    # ### end Alembic commands ###
