"""mails.rfc_message_id

Revision ID: 3568317481a7
Revises: 1cbb4c1bd861
Create Date: 2026-07-03 11:27:26.592998

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3568317481a7'
down_revision: str | None = '1cbb4c1bd861'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mails', sa.Column('rfc_message_id', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mails', 'rfc_message_id')
    # ### end Alembic commands ###
