"""respuesta_compras gmail_message_id

Revision ID: 4652ad871c0b
Revises: 8f9695de372c
Create Date: 2026-07-14 11:22:04.058551

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4652ad871c0b'
down_revision: str | None = '8f9695de372c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('respuestas_compras', sa.Column('gmail_message_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_respuestas_compras_gmail_message_id'), 'respuestas_compras', ['gmail_message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_respuestas_compras_gmail_message_id'), table_name='respuestas_compras')
    op.drop_column('respuestas_compras', 'gmail_message_id')
    # ### end Alembic commands ###
