"""tarea recordatorio

Revision ID: 64b8b66c0ca0
Revises: ad739e2a130c
Create Date: 2026-07-13 13:41:36.566783

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64b8b66c0ca0'
down_revision: str | None = 'ad739e2a130c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tareas', sa.Column('recordatorio', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tareas', 'recordatorio')
    # ### end Alembic commands ###
