"""tarea recordatorio_notificado

Revision ID: 684d14e7783a
Revises: 64b8b66c0ca0
Create Date: 2026-07-13 13:51:05.463597

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '684d14e7783a'
down_revision: str | None = '64b8b66c0ca0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'tareas',
        sa.Column(
            'recordatorio_notificado',
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tareas', 'recordatorio_notificado')
    # ### end Alembic commands ###
