"""mails_descartados

Revision ID: 8df3a2cafacc
Revises: 234f51c692a1
Create Date: 2026-06-30 10:32:22.808421

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8df3a2cafacc'
down_revision: str | None = '234f51c692a1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mails_descartados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gmail_message_id', sa.String(length=255), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('de', sa.String(length=320), nullable=True),
    sa.Column('asunto', sa.String(length=500), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mails_descartados_gmail_message_id'), 'mails_descartados', ['gmail_message_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mails_descartados_gmail_message_id'), table_name='mails_descartados')
    op.drop_table('mails_descartados')
    # ### end Alembic commands ###
