"""cliente cuenta principal y datos adicionales

Revision ID: 8f9695de372c
Revises: ad290482042f
Create Date: 2026-07-14 09:01:31.926247

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f9695de372c'
down_revision: str | None = 'ad290482042f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('cuenta_principal_id', sa.Integer(), nullable=True))
    op.add_column('clientes', sa.Column('tipo', sa.String(length=50), nullable=True))
    op.add_column('clientes', sa.Column('sector', sa.String(length=80), nullable=True))
    op.add_column('clientes', sa.Column('sitio_web', sa.String(length=255), nullable=True))
    op.add_column('clientes', sa.Column('telefono', sa.String(length=50), nullable=True))
    op.add_column('clientes', sa.Column('empleados', sa.Integer(), nullable=True))
    op.add_column('clientes', sa.Column('direccion_facturacion', sa.Text(), nullable=True))
    op.add_column('clientes', sa.Column('direccion_envio', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'clientes', 'clientes', ['cuenta_principal_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clientes', type_='foreignkey')
    op.drop_column('clientes', 'direccion_envio')
    op.drop_column('clientes', 'direccion_facturacion')
    op.drop_column('clientes', 'empleados')
    op.drop_column('clientes', 'telefono')
    op.drop_column('clientes', 'sitio_web')
    op.drop_column('clientes', 'sector')
    op.drop_column('clientes', 'tipo')
    op.drop_column('clientes', 'cuenta_principal_id')
    # ### end Alembic commands ###
