"""tarea subtipo

Revision ID: ad290482042f
Revises: 684d14e7783a
Create Date: 2026-07-13 15:45:42.449378

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad290482042f'
down_revision: str | None = '684d14e7783a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tareas', sa.Column('subtipo', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tareas', 'subtipo')
    # ### end Alembic commands ###
