"""tareas

Revision ID: ad739e2a130c
Revises: 13aef446d2f6
Create Date: 2026-07-13 13:06:34.523535

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad739e2a130c'
down_revision: str | None = '13aef446d2f6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tareas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=300), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('prioridad', sa.Enum('alta', 'media', 'baja', name='prioridad_tarea'), nullable=False),
    sa.Column('completada', sa.Boolean(), nullable=False),
    sa.Column('fecha_completada', sa.DateTime(timezone=True), nullable=True),
    sa.Column('oportunidad_id', sa.Integer(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['oportunidad_id'], ['oportunidades.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tareas_completada'), 'tareas', ['completada'], unique=False)
    op.create_index(op.f('ix_tareas_fecha_vencimiento'), 'tareas', ['fecha_vencimiento'], unique=False)
    op.create_index(op.f('ix_tareas_usuario_id'), 'tareas', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tareas_usuario_id'), table_name='tareas')
    op.drop_index(op.f('ix_tareas_fecha_vencimiento'), table_name='tareas')
    op.drop_index(op.f('ix_tareas_completada'), table_name='tareas')
    op.drop_table('tareas')
    # ### end Alembic commands ###
